# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: UnitTest

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

jobs:
  build:
    runs-on: macos-15
    steps:
    # チェックアウト
    - uses: actions/checkout@v4

    # Xcode バージョンの指定
    - name: Select Xcode
      run : sudo xcode-select -s '/Applications/Xcode_16.0.app/Contents/Developer'

    # ビルド
    - name: Xcode Build
      run:  xcodebuild -scheme  AsyncSwiftData -destination 'platform=iOS Simulator,name=iPhone 16,OS=18.1'

    # UnitTest実行
    - name: Run tests
      run: xcodebuild -scheme AsyncSwiftData -destination 'platform=iOS Simulator,name=iPhone 16,OS=18.1' test
